steps:
  - name: ":ubuntu: setup"
    command: apt-get install jq
  - wait
  - name: ":docker: build:dev"
    command: script/build
  - wait
  - name: ":node: test"
    command: sudo docker run 'playground-docker-image-buildkite:dev' npm test
  - wait
  - name: ":docker: build:optimize"
    command: script/build -o
