steps:
  - name: ":ubuntu: setup"
    command: apt-get install jq
  - wait
  - name: ":docker: build:base"
    command: script/build
  - wait
  - name: ":buildkite: meta"
    command: >
      version=$(jq -r '.version' < package.json);
      buildkite-agent meta-data set version-dev "$version";
  - wait
  - name: ":node: test"
    command: >
      sudo docker run 'yoshuawuyts/playground-docker-buildkite:base' npm test;
      if [ $? -eq 0 ]; then buildkite-agent meta-data set status 'passed'
      else; buildkite-agent meta-data set status 'failed'; fi
  - wait
  - name: ":docker: build:optimize"
    command: script/build -o
  - wait
  - name: ":docker: release"
    branches: "master"
    command: script/build -p
  - wait
  - name: ":buildkite: meta"
    command: >
      version=$(jq -r '.version' < package.json);
      buildkite-agent meta-data set version "$version";
