#!/bin/bash

version="$(jq '.version' < package.json | sed 's/"//g')"
commit="$(git log --oneline | head -1 | awk '{ print $1 }')"
name="playground-docker-image-buildkite"
date="$(date --iso-8601=seconds)"
username="yoshuawuyts"

run_build () {
  sudo docker build \
    -t "$name:dev" \
    -t "$name:$version" \
    --label "date=$date" \
    --label "commit=$commit" \
    --label "dockerfile=Dockerfile" \
    --label "repository=https://github.com/$username/$name" \
    .
}

run_optimize () {
  sudo docker build \
    -t "$name:latest" \
    -t "$name:$version" \
    --label "date=$date" \
    --label "commit=$commit" \
    --label "dockerfile=Dockerfile" \
    --label "repository=https://github.com/$username/$name" \
    .
}

usage () {
  printf 'Usage: script/build [options]'
}

# set CLI flags
args="$(getopt ho "$*")"
[ ! $? -eq 0 ] && { usage && exit 2; }
eval set -- "$args"

# parse CLI flags
while true; do
  case "$1" in
    -h ) usage ;;
    -o ) shift; run_optimize; break ;;
    * ) shift; run_build; break ;;
  esac
done
